# Generated by Django 3.0.4 on 2021-10-14 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0003_sentence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentence',
            name='sentence',
            field=models.CharField(max_length=1000),
        ),
    ]
